src/Yooocan.Web/Controllers/BlogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Yooocan.Dal;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Yooocan.Entities;
using Yooocan.Models.Blog;
using Microsoft.AspNetCore.Authorization;
using Yooocan.Entities.Blog;
using Yooocan.Logic;
using System.Collections.Generic;
using Yooocan.Logic.Options;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using Yooocan.Models.New.Stories;
using System;
using Yooocan.Logic.Extensions;
using System.Linq;
using System.Text.RegularExpressions;
using Yooocan.Logic.Images;
using Yooocan.Models;

namespace Yooocan.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlogController : BaseController
    {
        public BlogController(ApplicationDbContext context, IMapper mapper,
            ILogger<BlogController> logger, UserManager<ApplicationUser> userManager,
            HtmlSanitizer htmlSanitizer, IOptions<AzureStorageOptions> azureStorageOptions, RedisWrapper redisWrapper,
            ImageUrlOptimizer imageUrlOptimizer) : base(context, logger, mapper, userManager)
        {
            HtmlSanitizer = htmlSanitizer;
            RedisWrapper = redisWrapper;
            ImageUrlOptimizer = imageUrlOptimizer;
            AzureStorageOptions = azureStorageOptions.Value;
        }

        public HtmlSanitizer HtmlSanitizer { get; }
        public RedisWrapper RedisWrapper { get; }
        public ImageUrlOptimizer ImageUrlOptimizer { get; }
        public AzureStorageOptions AzureStorageOptions { get; }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePostModel model)
        {
            var post = new Post
            {
                Content = HtmlSanitizer.SanitizeHtml(model.Content.Replace(AzureStorageOptions.StoragePath, AzureStorageOptions.ImagesCdnPath)),
                Title = model.Title.Trim(),
                Description = model.Description.Trim(),
                UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),

            };
            if (!string.IsNullOrEmpty(model.HeaderImageUrl))
            {
                post.Images = new List<PostImage>
                            {
                                new PostImage
                                {
                                    Type = Enums.ImageType.Header,
                                    Url = model.HeaderImageUrl.Replace(AzureStorageOptions.StoragePath, AzureStorageOptions.ImagesCdnPath),
                                }
                            };
            }
            await Context.Posts.AddAsync(post);
            await Context.SaveChangesAsync();
            return RedirectToAction("Index", new { post.Id });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var existing = await Context.Posts.Include(x => x.Images)
                                              .SingleAsync(x => x.Id == id);

            var model = new CreatePostModel
            {
                Content = HtmlSanitizer.SanitizeHtml(existing.Content),
                Title = existing.Title,
                Description = existing.Description,
                HeaderImageUrl = existing.Images.FirstOrDefault(x => x.Type == Enums.ImageType.Header)?.Url
            };

            return View("Create", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreatePostModel model)
        {
            var existing = await Context.Posts.Include(x => x.Images)
                                              .SingleAsync(x => x.Id == id);

            existing.Content = HtmlSanitizer.SanitizeHtml(model.Content.Replace(AzureStorageOptions.StoragePath, AzureStorageOptions.ImagesCdnPath));
            existing.Title = model.Title.Trim();
            existing.Description = model.Description.Trim();
            var existingHeaderImage = existing.Images.FirstOrDefault(x => x.Type == Enums.ImageType.Header);
            if (model.HeaderImageUrl != null && model.HeaderImageUrl != existingHeaderImage?.Url)
            {
                if(existingHeaderImage != null)
                    existingHeaderImage.IsDeleted = true;
                existing.Images.Add(new PostImage
                {
                    Type = Enums.ImageType.Header,
                    Url = model.HeaderImageUrl.Replace(AzureStorageOptions.StoragePath, AzureStorageOptions.ImagesCdnPath),
                });
            }

            await Context.SaveChangesAsync();
            await RedisWrapper.RedisDatabase.KeyDeleteAsync(GetKeyName(id));

            return RedirectToAction("Index", new { id });
        }

        public async Task<ActionResult> All()
        {
            var posts = await Context.Posts.IgnoreQueryFilters().AsNoTracking().ToListAsync();
            var models = Mapper.Map<List<Post>, List<PostModel>>(posts);

            return View(models);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TogglePublish(int id)
        {
            var post = await Context.FindAsync<Post>(id);
            post.PublishDate = post.PublishDate == null ? DateTime.UtcNow : (DateTime?)null;
            post.LastUpdateDate = DateTime.Now;
            await Context.SaveChangesAsync();
            await InvalidatePostCache(id);
            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ToggleDelete(int id)
        {
            var post = await Context.Posts.IgnoreQueryFilters().Where(x => x.Id == id).SingleAsync();
            post.IsDeleted = !post.IsDeleted;
            post.LastUpdateDate = DateTime.Now;
            await Context.SaveChangesAsync();
            await InvalidatePostCache(id);
            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ToggleFeatured(int id)
        {
            var post = await Context.FindAsync<Post>(id);
            var currentlyFeaturedPosts = await Context.Posts.Where(x => x.Order != 0).ToListAsync();
            post.Order = post.Order < 0 ? 0 : -1;
            currentlyFeaturedPosts.ForEach(p => p.Order = 0);

            await Context.SaveChangesAsync();
            return RedirectToAction(nameof(All));
        }

        private async Task InvalidatePostCache(int id)
        {
            await RedisWrapper.RedisDatabase.KeyDeleteAsync(GetKeyName(id));
        }

        [HttpGet]
        [Route("Blog/{id:int}/{title?}", Name = "Blog")]
        [AllowAnonymous]
        public async Task<ActionResult> Index(int id, string title)
        {
            var model = await RedisWrapper.GetModelAsync(GetKeyName(id), async () =>
            {
                var post = await Context.Posts
                                        .Include(x => x.Images)
                                        .Include(x => x.User)
                                        .AsNoTracking()
                                        .SingleOrDefaultAsync(x => x.Id == id);
                var postModel = Mapper.Map<StoryModel>(post);
                postModel.Paragraphs[0].Text = OptimizeImages(postModel.Paragraphs[0].Text);

                var lastPosts = await Context.Posts
                                        .Include(x => x.Images)                                        
                                        .Where(x => x.Id != id && x.PublishDate != null)
                                        .OrderByDescending(x => x.InsertDate)
                                        .Take(2)
                                        .AsNoTracking()
                                        .ToListAsync();
                var queriedIds = lastPosts.Select(x => x.Id)
                                            .Union(new[] { id })
                                            .ToList();

                var randomPost = await Context.Posts.Include(x => x.Images)
                                                    .Where(x => !queriedIds.Contains(x.Id) && x.PublishDate != null)
                                                    .OrderBy(x => Guid.NewGuid())
                                                    .AsNoTracking()
                                                    .FirstOrDefaultAsync();
                var randomPostImage = await Context.PostImages.AsNoTracking()
                                                              .Where(x => x.PostId == randomPost.Id)
                                                              .FirstOrDefaultAsync();
                if (randomPost != null)
                {
                    randomPost.Images = new List<PostImage> { randomPostImage };
                    lastPosts.Add(randomPost);
                }

                var lastPostsCards = Mapper.Map<List<StoryCardModel>>(lastPosts);
                postModel.RelatedStories = lastPostsCards;

                return postModel;
            }, TimeSpan.FromDays(1));

            if (model == null)
                return NotFound();

            if (title != model.Title.ToCanonical())
                return RedirectToRoute(new { id, Title = model.Title.ToCanonical() });            

            return View("../Story/Index", model);
        }

        private string GetKeyName(int postId)
        {
            return string.Format(RedisKeys.BlogPost, postId);
        }

        private string OptimizeImages(string content)
        {
            var images = Regex.Matches(content, $@"<img src=""([^""]*)""").Cast<Match>().Select(x => x.Groups[1].Value).ToList();
            var optimizedImages = images.Select(x => ImageUrlOptimizer.GetOptimizedUrl(x, 900)).ToList();

src/Yooocan.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Yooocan.Dal;
using Yooocan.Entities;
using Yooocan.Logic;
using Yooocan.Models;
using System.Linq;
using System.Text.RegularExpressions;
using System.Net.Http;
using Yooocan.Logic.Options;
using Microsoft.Extensions.Options;
using Yooocan.Logic.Images;
using Yooocan.Web.ActionFilters;

namespace Yooocan.Web.Controllers
{
    public class ImageController : BaseController
    {
        private readonly IBlobUploader _blobUploader;
        private readonly AzureImageResizer _azureImageResizer;
        private AzureStorageOptions _storageOptions;

        public ImageController(ApplicationDbContext context, ILogger<ImageController> logger, IMapper mapper, UserManager<ApplicationUser> userManager, IBlobUploader blobUploader, IOptions<AzureStorageOptions> storageOptionsWrapper, AzureImageResizer azureImageResizer) : base(context, logger, mapper, userManager)
        {
            _blobUploader = blobUploader;
            _azureImageResizer = azureImageResizer;
            _storageOptions = storageOptionsWrapper.Value;
        }

        [HttpPost]
        [Authorize]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        public async Task<ActionResult> UploadImages(List<IFormFile> images, string containerName = "images", int? width = null, int? height = null, int quality = 90)
        {
            var urls = await UploadImagesInternal(images, containerName, width, height, quality);
            return Ok(urls);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        public async Task<ActionResult> UploadImageMce(IFormFile file)
        {
            var url = (await UploadImagesInternal(new List<IFormFile> { file }))[0];
            return Ok($@"{{""location"": ""{url}""}}");
        }

        private async Task<List<string>> UploadImagesInternal(List<IFormFile> images, string containerName = "images", int? width = null, int? height = null, int quality = 90)
        {
            var models = Mapper.Map<List<UploadFileModel>>(images);
            try
            {
                await _blobUploader.UploadFilesAsync(models, containerName, width, height);
            }
            catch (Exception exception)
            {
                var contents = GetFileContents(images);
                Logger.LogError(new EventId(176253), exception, "Failed to upload images: " +
                                                    string.Join("\r\n", contents.Select(x => $"Content-Type: {x.Type}, Base64 Contents: {x.Base64Content}\r\n")));
                throw;
            }
            var urls = models.Select(x => x.Url).ToList();
            return urls;
        }       

        [Route("/Image/Get/{*path}")]
        public async Task<HttpResponseMessage> Get(string path, [FromQuery(Name = "w")]int? width, [FromQuery(Name = "h")]int? height,
            [FromQuery(Name = "m")]TransformationMode mode = TransformationMode.Cover)
        {
            return await _azureImageResizer.GenerateOrGetResizedImage(path, mode, width, height);
        }

        private IEnumerable<(string Type, string Base64Content)> GetFileContents(IEnumerable<IFormFile> files)
        {
            foreach (var file in files)
            {
                using (var stream = file.OpenReadStream())
                using (var ms = new MemoryStream())
                {
                    stream.CopyTo(ms);
                    var base64 = Convert.ToBase64String(ms.ToArray());
                    yield return (file.ContentType, base64);
                }
            }
        }

        [HttpPost]
        [Authorize]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        public async Task<ActionResult> UploadDataUriImages(string dataUri, string containerName, int quality = 95)
        {
            var matches = Regex.Match(dataUri, @"data:(?<type>.+?);base64,\s*?(?<data>.+)");
            var base64 = matches.Groups["data"].Value;
            var bytes = Convert.FromBase64String(base64);

            using (var memoryStream = new MemoryStream(bytes))
            {
                var url = await _blobUploader.UploadStreamAsync(memoryStream, containerName, Guid.NewGuid().ToString("N"), quality: quality);
                return Ok(url);
            }
        }
    }
}

src/Yooocan.Web/Views/Blog/All.cshtml
@model List<Yooocan.Models.Blog.PostModel>
@using Yooocan.Logic.Extensions
@using System.Text.Encodings.Web
@{
    ViewBag.Title = "Blog control panel";
    var featuredPostId = Model.Where(x => x.Order != 0).OrderBy(x => x.Order).FirstOrDefault()?.Id;
}
<script>
    function confirmPublish(isPublished, title) {
        return !isPublished || confirm("Do you want to unpublish post '" + title +
            "'? If you publish this post in the future, it will reset the publish date (appears at the top of the post) to the last publish date.");
    }

    function confirmDelete(isDeleted, title) {
        return isDeleted || confirm("Do you want to delete post '" + title +
            "'? All links to this post will no longer work.");
    }
</script>
<p>To update home page with the currently featured post immediately <a asp-controller="Admin" asp-action="DeleteCache">clear cache here</a></p>
<table>
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>View</th>
        <th>Edit</th>
        <th>Publish</th>
        <th>Make Featured</th>
        <th>Delete</th>
    </tr>
    @foreach (var post in Model)
    {
        <tr>
            <td>@post.Id</td>
            <td>@post.Title</td>
            <td><a asp-action="Index" asp-route-id="@post.Id" asp-route-title="@post.Title.ToCanonical()" target="_blank">View</a></td>
            <td><a asp-action="Edit" asp-route-id="@post.Id" target="_blank">Edit</a></td>
            <td>
                <form asp-action="TogglePublish" asp-route-id="@post.Id" method="post" onsubmit="return confirmPublish(@(post.PublishDate == null ? "false" : "true"), '@JavaScriptEncoder.Default.Encode(post.Title)');">
                    <button class="btn waves-effect waves-light @(post.PublishDate == null ? "green" : "red")">
                        @(post.PublishDate == null ? "Publish" : "Unpublish")
                    </button>
                </form>
            </td>
            <td>
                <form asp-action="ToggleFeatured" asp-route-id="@post.Id" method="post">
                    <button class="btn waves-effect waves-light @(post.Id == featuredPostId ? "blue" : "grey")">
                        @(post.Id == featuredPostId ? "Unfeature" : "Feature")
                    </button>
                </form>
            </td>
            <td>
                <form asp-action="ToggleDelete" asp-route-id="@post.Id" method="post" onsubmit="return confirmDelete(@(post.IsDeleted ? "true" : "false"), '@JavaScriptEncoder.Default.Encode(post.Title)');">
                    <button class="btn waves-effect waves-light @(post.IsDeleted ? "green" : "red")">
                        @(post.IsDeleted ? "Undelete" : "Delete")
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

src/Yooocan.Web/Views/Blog/Create.cshtml
@model Yooocan.Models.Blog.CreatePostModel
@{
    ViewBag.Title = "Create/Edit blog post";
}
@section head {
    <embedCss href="/css/Blog/Create.css" />
    <link rel="stylesheet" href="/lib/croppie/croppie.css" />
}
<h1 class="center">Create/Edit post</h1>
<form method="post">
    <input type="hidden" asp-for="HeaderImageUrl" />
    <div class="profile-basic-info" id="header-image-uploader" data-upload-url="@Url.Action("UploadDataUriImages", "Image")">
        <div class="header picture-preview" style="background-image: url('@Model?.HeaderImageUrl')">
            <input type="hidden" class="picture-data-uri" id="headerImageDataUri" />
            <div class="content center">
                <h3 class="title"></h3>
                <button class="waves-effect waves-teal btn upload-picture-button center" type="button" id="choose-cover">CHOOSE COVER</button>
                <input type="file" class="picture-upload" accept="image/*" style="display: none;" />
                <div id="story-meta">
                    @*<i class="material-icons">watch_later</i><span class="date">@DateTime.UtcNow.ToString("MMMM dd yyyy hh:mm tt")</span>
                        <i class="material-icons fav">favorite</i>
                        <span class="fav-count">0</span>
                        <img src="/images/chat-story.svg" asp-append-version="true" id="chat-icon" />
                        <span class="comments-count">0</span>*@
                </div>
            </div>
        </div>
    </div>
    <div class="modal" id="preview-header-modal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="crop-preview"></div>
                <div class="center" style="padding-bottom: 15px">
                    <button type="button" class="take-picture btn btn-primary">Looks good</button>
                    <button type="button" class="close-modal btn btn-default">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col s8">
                <div class="input-field">
                    <input asp-for="Title" />
                    <label asp-for="Title"></label>            
                    <span asp-validation-for="Title" class="red-text"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s8">
                <div class="input-field">
                    <input asp-for="Description" />
                    <label asp-for="Description"></label>
                    <span asp-validation-for="Description" class="red-text"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s8">
                <div class="input-field">
                    <textarea asp-for="Content" data-upload-url="@Url.Action("UploadImageMce", "Image")"></textarea>
                    <label asp-for="Content" id="content-label"></label>
                </div>
            </div>
        </div>
        <div>
            <input type="submit" class="btn" />
        </div>
    </div>
</form>
@section scripts {
    <script src='https://cdn.tinymce.com/4/tinymce.min.js' asp-fallback-src="/lib/tinymce/tinymce.js" asp-fallback-test="window.tinymce"></script>
    <script src="/dist/Blog/create.js" asp-append-version="true"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
}