src/Yooocan.Web/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Yooocan.Dal;
using Yooocan.Entities;
using Yooocan.Logic;
using Yooocan.Logic.Messaging;
using Yooocan.Models;
using Yooocan.Models.Vendors;
using Yooocan.Web.ActionFilters;

namespace Yooocan.Web.Controllers
{
    [Authorize]
    public class VendorController : BaseController
    {
        private readonly IEmailSender _emailSender;
        private readonly IOldProductLogic _productLogic;

        public VendorController(ApplicationDbContext context, ILogger<VendorController> logger, IMapper mapper, UserManager<ApplicationUser> userManager,
            IEmailSender emailSender, IOldProductLogic productLogic) : base(context, logger, mapper, userManager)
        {
            _emailSender = emailSender;
            _productLogic = productLogic;
        }

        #region Admin Actions
    
        [Authorize(Roles = "Admin")]
        public ActionResult Index(bool showDeleted = false)
        {
            return RedirectToAction("Index", "Company");
            //return OldIframeContainer();
        }
    
        [Authorize(Roles = "Admin")]
        public ActionResult IndexOld(bool showDeleted = false)
        {
            ViewBag.ShowDeleted = showDeleted;

            var query = Context.Vendors.Where(x => x.AltoId != null).AsQueryable();
            if (!showDeleted)
            {
                query = query.Where(x => !x.IsDeleted);
            }
            var vendors = query.Include(x => x.Products)
                               .ToList();
            var models = Mapper.Map<IEnumerable<VendorListModel>>(vendors);
            return OldView(models);
        }

        // GET: Vendor/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vendor/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return OldIframeContainer();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateOld()
        {
            return OldView();
        }

        // POST: Vendor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(CreateVendorModel model)
        {
            try
            {
                if (Context.Vendors.Any(x => x.Name == model.Name))
                {
                    ModelState.AddModelError("Name", "Vendor name already exists");
                    return OldView(model);
                }

                var vendor = Mapper.Map<Vendor>(model);
                Context.Vendors.Add(vendor);
                Context.SaveChanges();
                //return RedirectToAction("Details", new {id = vendor.Id});
                return RedirectToAction("Index");
            }
            catch
            {
                return OldView();
            }
        }

        // GET: Vendor/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vendor/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        public async Task<ActionResult> Delete(int id)
        {
            return await ToggleDelete(id, true);           
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        public async Task<ActionResult> Undelete(int id)
        {
            return await ToggleDelete(id, false);
        }

        private async Task<ActionResult> ToggleDelete(int id, bool delete)
        {
            var vendor = await Context.Vendors.Include(x => x.Products)
                                              .SingleAsync(x => x.Id == id);
            vendor.IsDeleted = delete;
            vendor.LastUpdateDate = DateTime.UtcNow;

            foreach (var product in vendor.Products)
            {
                product.IsDeleted = delete;
                product.IsPublished = false;
                product.LastUpdateDate = DateTime.UtcNow;
            }

            await Context.SaveChangesAsync();

            return Redirect(Request.Headers["Referer"]);
        }

        #endregion

        #region SignUp - Registration

        [Authorize(Policy = "MyVendor")]
        public ActionResult SignUp(int id)
        {
            return OldIframeContainer();
        }

        // GET: Vendor/SignUpOld/5
        [Authorize(Policy = "MyVendor")]
        public async Task<ActionResult> SignUpOld(int id)
        {
            var vendor = await Context.Vendors.Where(x => x.Id == id)
                                              .SingleOrDefaultAsync();
            if (vendor == null)
            {
                Logger.LogWarning($"Vendor id {id} not found");

                return NotFound();
            }

            var vendorModel = Mapper.Map<VendorModel>(vendor);

            return OldView(vendorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "MyVendor")]
        public async Task<ActionResult> SignUp(int id, VendorModel model)
        {
            var vendorFromDb = await Context.Vendors.Where(x => x.Id == id)
                                                    .SingleOrDefaultAsync();

            model.Id = vendorFromDb.Id;
            model.CommercialTerms = vendorFromDb.CommercialTerms;
            model.CommercialTermsOther = vendorFromDb.CommercialTermsOther;
            model.CommercialTermsRate = vendorFromDb.CommercialTermsRate;

            Mapper.Map(model, vendorFromDb);

            if (!User.IsInRole("Admin"))
            {
                vendorFromDb.OnBoardingContactPersonEmail = model.ContactPersonEmail;
                vendorFromDb.OnBoardingDate = DateTime.UtcNow;
            }
            vendorFromDb.LastUpdateDate = DateTime.UtcNow;

            await Context.SaveChangesAsync();

            return User.IsInRole("Admin") ? RedirectToAction(nameof(MyProducts), new {Id = id}) : RedirectToAction(nameof(ConfirmSignUp));
        }

        public ActionResult ConfirmSignUp()
        {
            return OldView();
        }

        #endregion

        #region MyProducts

        [Authorize]
        public async Task<ActionResult> MyProductsOld()
        {
            var vendorId = int.Parse(User.FindFirst("vendor").Value);
            var model = await _productLogic.GetMyProducts(vendorId);
            if (model == null)
                return NotFound();

            return OldView(model);
        }

        public ActionResult MyProducts(int? id)
        {
            return OldIframeContainer();
        }

        [Route("Vendor/MyProductsOld/{id:int}")]
        [Authorize(Policy = "MyVendor")]
        public async Task<ActionResult> MyProductsOld(int id)
        {
            var model = await _productLogic.GetMyProducts(id);
            return model == null ? NotFound() : OldView(model);
        }

        #endregion

        #region Pre Registration
        [AllowAnonymous]
        public ActionResult Register()
        {
            return RedirectToAction("Register", "Company");
            //return OldIframeContainer();
        }

        [AllowAnonymous]
        public ActionResult RegisterOld()
        {
            return OldView();
        }

        [HttpPost]
        [ServiceFilter(typeof(CsrfHeadersValidationFilter))]
        [AllowAnonymous]
        public async Task<ActionResult> RegisterOld(RegisterVendorModel model)
        {
            if (ModelState.IsValid)
            {
                var vendorRegistration = Mapper.Map<VendorRegistration>(model);
                Context.VendorRegistrations.Add(vendorRegistration);
                Context.SaveChanges();

                var content = JsonConvert.SerializeObject(model, Formatting.Indented, new Newtonsoft.Json.Converters.StringEnumConverter());
                await _emailSender.SendEmailAsync(null, "moshe@yoocantech.com", "Vendor registered", content, "VendorRegistered", null);

                return RedirectToAction(nameof(RegisterConfirmation));
            }

            LogModelStateErrors();

            return OldView(model);
        }

        public ActionResult RegisterConfirmation()
        {
            return OldView();
        }
        #endregion
    }
}

src/Yooocan.Web/Views/Admin/AddAmazonProducts.cshtml
@model Yooocan.Models.Admin.AddAmazonProductModel
@{
    ViewBag.Title = "Add Amazon Product";
    Layout = "_Layout";
}

<h4>@ViewBag.Title</h4>
<form method="post" id="add-product">
    <input asp-for="Asin" maxlength="10" required style="width: 200px" placeholder="ASIN" />
    <button class="btn">Add</button>
</form>
@if (Model.ProductId != 0)
{
    <p>
        Product added. <br />
        <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.ProductId" target="_blank">Edit</a><br/>
        <a asp-controller="Vendor" asp-action="MyProducts" asp-route-id="@Model.AmazonVendorId" target="yoocan-amazon-products">View Amazon Products</a>
    </p>
}
@section scripts {
    <script>
        $('#add-product').submit(function () {
            $(this).find('button').first().prop('disabled', true);
        });
    </script>
}

src/Yooocan.Web/Views/Admin/Dashboard.cshtml
@model DashboardModel

@{
    ViewBag.Title = "yoocan Dashboard";
}
<style>
    col {
        height: 160px;
    }
</style>
<h4 class="text-center" style="margin-bottom: 20px;">
    HERE ARE SOME SYSTEM FACTS FOR YOU MOSHE ❤
</h4>
<div class="container">
    <div class="row text-center">
        <div class="col m3 s6 ">
            <h1>@Model.Stories</h1>
            <h4>STORIES</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.ProductRecommendations</h1>
            <h4>PRODUCT RECOMMEN-DATIONS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.TipsArticles</h1>
            <h4>Tips Articles</h4>
        </div>
        <div class="col m3 s6 ">
            <h1 class="red-if-big">@Model.PendingStories</h1>
            <h4>PENDING STORIES</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.Products</h1>
            <h4>PRODUCTS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.Vendors</h1>
            <h4>VENDORS WITH PRODUCTS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.Users</h1>
            <h4>USERS</h4>
            <a asp-route="ConfirmedUsersEmails">Confirmed emails csv</a>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.ServiceProviders</h1>
            <h4>SERVICE PROVIDERS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1 class="red-if-big">@Model.PendingServiceProviders</h1>
            <h4>PENDING SERVICE PROVIDERS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.StoryImages</h1>
            <h4>STORY IMAGES</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.ProductImages</h1>
            <h4>PRODUCT IMAGES</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.StoryVideos</h1>
            <h4>STORY VIDEOS</h4>
        </div>
        <div class="col m3 s6 ">
            <h1>@Model.ProductVideos</h1>
            <h4>PRODUCT VIDEOS</h4>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $('.red-if-big').each(function () {
            if (parseInt(this.innerHTML.trim()) > 0) {
                this.style.color = 'red';
                $(this).next().css('color', 'red');
            }
        });
    </script>
}

src/Yooocan.Web/Views/Admin/DeleteCache.cshtml
@using Yooocan.Logic
<div class="container" style="text-align: center; margin-top: 30px;">
    <div class="row">
        <form class="col s12" method="POST">
            <input type="hidden" name="resource" value="@RedisKeys.HomeModel" />
            <button class="btn">DELETE HOMEPAGE CAHCE</button>
        </form>
    </div>
    <div class="row">
        <form class="col s12" method="POST">
            <input type="hidden" name="resource" value="@RedisKeys.HomeStoryFeed" />
            <button class="btn">DELETE HOMEPAGE STORIES CACHE</button>
        </form>
    </div>
    <div class="row">
        <form class="col s12" method="POST">
            <input type="hidden" name="resource" value="@RedisKeys.HomeModelMobile" />
            <button class="btn">DELETE MOBILE STORIES HOMEPAGE CACHE</button>
        </form>
    </div>
</div>

src/Yooocan.Web/Views/Admin/FeaturedStories.cshtml
@using System.Security.Claims
@using Yooocan.Enums
@model List<Yooocan.Models.Admin.FeaturedStoryModel>
<div class="container">
    @FeaturedType.Header.Humanize() = @((int)FeaturedType.Header)<br />
    @FeaturedType.EditorPick.Humanize() = @((int)FeaturedType.EditorPick)<br />
    @FeaturedType.Feed.Humanize() = @((int)FeaturedType.Feed)

    <div>
        <button class="btn" type="button" id="add-row">ADD ROW</button>
    </div>
    <br />
    <table class="responsive-table striped" id="featured-table">
        <thead>
            <tr>
                <th>Story #ID</th>
                <th>Title</th>
                <th>Featured place</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var story in Model)
            {
                <tr>
                    <td data-field="StoryId">@story.StoryId</td>
                    <td>@story.Title</td>
                    <td data-field="FeaturedType">@((int)story.FeaturedType)</td>
                    <td><button type="button" class="btn-flat delete">Remove</button></td>
                </tr>
            }
        </tbody>
    </table>
    <div style="margin-top: 30px;">
        <button id="save-changes" class="btn right" type="button">SAVE CHANGES</button>
    </div>
</div>

@section scripts{
    <script>
        var newRow = `<tr>
            <td data-field="StoryId"><input type="number"/></td>
            <td></td>
            <td data-field="FeaturedType"><input type="number" min="1" max="3"/></td>
            <td><button class="btn delete">Remove</button></td>
        </tr>`;
        $('#add-row').click(function () {
            $(newRow).appendTo('#featured-table tbody').find('input:first').focus();
            return false;
        });

        $('#featured-table').on('click', '.delete', function () {
            $(this).closest('tr').remove();
            return false;
        });

        $('#save-changes').click(() => {
            var data = $('#featured-table tbody tr').map(function () {
                var o = {};
                $(this).find('td[data-field]').each(function () {
                    o[$(this).data('field')] = $(this).find('input').val() || this.innerHTML.trim();
                });
                return o;
            }).get();
            console.log(data);
            window.x = data;
            $.ajax({
                    url: '@Url.Action("FeaturedStories")',
                    type: 'POST',
                    data: JSON.stringify(data),
                    contentType: 'application/json'
                })
                .done(function() {
                    window.location.reload();
                })
                .fail(function() {
                    Materialize.toast('Sorry @User.FindFirstValue(ClaimTypes.GivenName) :( Something went wrong!, call Doron (not on Shabat!)', 10000);
                });
            return false;
        });
    </script>

}

src/Yooocan.Web/Views/Admin/StoryOfTheDay.cshtml
<form asp-action="StoryOfTheDay" method="post">
    <div asp-validation-summary="All"></div>
    <h3 class="center">Send story of the day email</h3>
    <div class="row">
        <div class="col s12 m4 offset-m4 input-field ">
            <input id="id" name="id" placeholder="Story id"/>
            <label for="id">STORY ID</label>
        </div>
        <div class="col s12 m4 offset-m4 input-field ">
            <textarea name="text" class="materialize-textarea" placeholder="Highlight of the story"></textarea>
        </div>
        <div class="col s12 m4 offset-m4 input-field ">
            <input id="recipient" name="recipient" placeholder="Use for test before sending" />
            <label for="recipient">TEST EMAIL ADDRESS</label>
        </div>
    </div>
    <div class="row">
        <div class="col m8">
            <button type="submit" class="btn right waves-effect waves-light" style="border-radius: 100px; background-color: #5c8dde;">Send Emails</button>
        </div>
    </div>
</form>

src/Yooocan.Web/Views/Admin/StoryServiceProviders.cshtml
<h2>Set service providers</h2>
<h4 class="text-center">@ViewBag.Title (@ViewBag.Id)</h4>
<form asp-action="StoryServiceProviders" method="post" class="form-horizontal">
    <div class="form-group" style="margin-top: 30px;">
        <label for="serviceProviderIds" class="col-md-3 control-label">Service providers</label>
        <div class="col-md-9">
            <input name="serviceProviderIds" id="serviceProviderIds" placeholder="Comma separated" class="form-control" value="@ViewBag.ServiceProviders" />
        </div>
    </div>

    <input type="submit" class="btn btn-primary col-md-offset-3" value="Save changes" />
</form>